[tool.poetry]
name = "idl2js"
version = "0.1.0"
description = ""
authors = ["Sergey Reshetnikov <resh.sersh@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"

antlr4-python3-runtime = "^4.8"
attrs = "^19.3.0"
stringcase = "^1.2.0"

[tool.poetry.dev-dependencies]
mypy = "^0.782"
pylint = "^2.5.3"
pytest = "^5.4.3"
pytest-cov = "^2.9.0"

sphinx = "^3.1.1"
sphinx_rtd_theme = "^0.5.0"
m2r = "^0.2.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
