[tool.poetry]
name = "idl2js"
version = "0.1.0"
description = "Grammar-based Fuzzer that uses WebIDL as a grammar."
authors = ["Sergey Reshetnikov <resh.sersh@gmail.com>"]
license = "Apache-2.0"

readme = "README.md"
repository = "https://github.com/PrVrSs/idl2js"
homepage = "https://github.com/PrVrSs/idl2js"

keywords = [
    "WebIDL",
    "fuzzer",
    "ast",
    "grammar",
    "fuzzing",
    "transpiler",
]

[tool.poetry.dependencies]
python = "^3.9"

antlr4-python3-runtime = "^4.9.2"
attrs = "^19.3.0"
more_itertools = "^8.4.0"
stringcase = "^1.2.0"
click = "^7.1.2"
graphviz = "^0.16"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
pylint = "^2.8.2"
pytest = "^5.4.3"
pytest-cov = "^2.9.0"

m2r = "^0.2.1"
sphinx = "^3.1.1"
sphinx_rtd_theme = "^0.5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
