[tool.poetry]
name = "idl2js"
version = "0.1.0"
description = ""
authors = ["Sergey Reshetnikov <resh.sersh@gmail.com>"]
license = "BSD-4-Clause"

[tool.poetry.dependencies]
python = "^3.8"

attrs = "^19.3.0"
pywebidl2 = "^0.1.3"
stringcase = "^1.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
pytest-cov = "^2.9.0"
pylint = "^2.5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
